# -*- coding: utf-8 -*-
"""Convertir mb a kb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1li6MAmHBjFEMQjV6_TNH7fjnMNySodAy
"""

import tensorflow as tf
import numpy as np
import os

kb = np.array([1024, 2048, 3072, 5120, 51200, 102400, 25600], dtype=float)
mb = np.array([1, 2, 3, 5, 50, 100, 25], dtype=float)

capa1 = tf.keras.layers.Dense(units = 4, input_shape=[1])
capa2 = tf.keras.layers.Dense(units = 3)
capa3 = tf.keras.layers.Dense(units = 2)
capa4 = tf.keras.layers.Dense(units = 1)
modelo = tf.keras.Sequential([capa1, capa2, capa3, capa4])

modelo.compile(
    optimizer = tf.keras.optimizers.Adam(0.1),
    loss = 'mean_squared_error'
)

os.system("clear || cls")
os.system("color 0a")
print("Comenzando entrenamiento...")
historial = modelo.fit(kb, mb, epochs=2500, verbose=False)
print("Modelo entrenado!")

import matplotlib.pyplot as plt
plt.xlabel("# Epoca")
plt.ylabel("Magnitud de périda")
plt.plot(historial.history["loss"])
plt.show()

print("Predicción")
kilos = np.array([35048.0])
resultado = modelo.predict(kilos)
print(f"{kilos} KB equivalen a {resultado[0][0]} MB (aproximadamente)")

print("Variables internas del modelo")
print(f"{capa1.get_weights()}")
print(f"{capa2.get_weights()}")
print(f"{capa3.get_weights()}")
print(f"{capa4.get_weights()}")